# backend/functions/rfp-extraction/shared/models/db_models.py

import os
from typing import List, Optional
from datetime import date
from sqlalchemy import String, Integer, ForeignKey, Text, Boolean, Date, create_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from pgvector.sqlalchemy import Vector  # valid for Azure Postgres with pgvector extension

# Define the database URL (Use an environment variable in production)
# Format for Azure: postgresql+psycopg2://<user>:<password>@<host>/<dbname>?sslmode=require
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql+psycopg2://user:password@localhost/rfp_db")

class Base(DeclarativeBase):
    pass

class Source(Base):
    """
    Represents the origin of the data (e.g., Previous RFP, Seismic, Qvidian).
    """
    __tablename__ = "source"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(String(255))
    # 'type' is a reserved keyword in Python, so we map it, but keep the SQL column name 'type'
    source_type: Mapped[Optional[str]] = mapped_column("type", String(100))

    # Relationship: One Source -> Many RFPs
    rfps: Mapped[List["RFP"]] = relationship(back_populates="source")

    def __repr__(self) -> str:
        return f"<Source(name={self.name})>"

class RFP(Base):
    """
    Represents a Request for Proposal event or document collection.
    """
    __tablename__ = "rfp"

    id: Mapped[int] = mapped_column(primary_key=True)
    source_id: Mapped[int] = mapped_column(ForeignKey("source.id"))
    client_name: Mapped[Optional[str]] = mapped_column(String(255))
    publish_date: Mapped[Optional[date]] = mapped_column(Date)
    responsible_desk: Mapped[Optional[str]] = mapped_column(String(100))
    format: Mapped[Optional[str]] = mapped_column(String(50))

    # Relationships
    source: Mapped["Source"] = relationship(back_populates="rfps")
    questions: Mapped[List["Question"]] = relationship(back_populates="rfp")
    qa_histories: Mapped[List["QAHistory"]] = relationship(back_populates="origin_rfp")

    def __repr__(self) -> str:
        return f"<RFP(client={self.client_name}, date={self.publish_date})>"

class Question(Base):
    """
    Individual questions extracted from an RFP.
    """
    __tablename__ = "question"

    id: Mapped[int] = mapped_column(primary_key=True)
    rfp_id: Mapped[int] = mapped_column(ForeignKey("rfp.id"))
    domain_id: Mapped[int] = mapped_column(Integer, nullable=False, index=True) 
    status: Mapped[Optional[str]] = mapped_column(String(50)) # e.g., 'Open', 'Assigned', 'Closed'
    content_text: Mapped[Optional[str]] = mapped_column(Text)

    # Relationships
    rfp: Mapped["RFP"] = relationship(back_populates="questions")
    answers: Mapped[List["Answer"]] = relationship(back_populates="question")
    qa_histories: Mapped[List["QAHistory"]] = relationship(back_populates="question")

    def __repr__(self) -> str:
        return f"<Question(id={self.id}, status={self.status})>"

class Answer(Base):
    """
    Drafts or final answers generated by agents or humans.
    """
    __tablename__ = "answer"

    id: Mapped[int] = mapped_column(primary_key=True)
    question_id: Mapped[int] = mapped_column(ForeignKey("question.id"))
    content_text: Mapped[Optional[str]] = mapped_column(Text)
    status: Mapped[Optional[str]] = mapped_column(String(50)) # e.g., 'Draft', 'Approved'
    is_final_version: Mapped[bool] = mapped_column(Boolean, default=False)

    # Relationships
    question: Mapped["Question"] = relationship(back_populates="answers")
    qa_histories: Mapped[List["QAHistory"]] = relationship(back_populates="answer")

    def __repr__(self) -> str:
        return f"<Answer(id={self.id}, final={self.is_final_version})>"

class QAHistory(Base):
    """
    Historical log or Vector Store entry for RAG (Retrieval Augmented Generation).
    Stores the embedding of the question for semantic search.
    """
    __tablename__ = "qa_history"

    id: Mapped[int] = mapped_column(primary_key=True)
    question_id: Mapped[int] = mapped_column(ForeignKey("question.id"))
    answer_id: Mapped[int] = mapped_column(ForeignKey("answer.id"))
    origin_rfp_id: Mapped[int] = mapped_column(ForeignKey("rfp.id"))
    
    # Vector column. 1536 is the dimension for OpenAI text-embedding-ada-002 / 3-small.
    # Adjust dimensions based on your embedding model (e.g., 768 for HuggingFace, 1536 for OpenAI).
    question_embedding_vect: Mapped[Optional[List[float]]] = mapped_column(Vector(1536))

    # Relationships
    question: Mapped["Question"] = relationship(back_populates="qa_histories")
    answer: Mapped["Answer"] = relationship(back_populates="qa_histories")
    origin_rfp: Mapped["RFP"] = relationship(back_populates="qa_histories")

    def __repr__(self) -> str:
        return f"<QAHistory(id={self.id})>"
